M_DJ_P_v2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", HomePageView.as_view(), name='home'),
    path("filter/", FilterMoviesView.as_view(), name='filter'),
    path("add-rating/", AddStarRating.as_view(), name='add_rating'),
    path("<slug:slug>/", MovieDetailView.as_view(), name='movie_detail'),
    path("review/<int:pk>/", AddReviewView.as_view(), name="add_view"),
    path("director/<str:slug>/", DirectorDetailView.as_view(), name="director")
]

movies/models.py
from django.db import models
from datetime import date

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(verbose_name="Название категории", max_length=40)
    description = models.TextField(verbose_name="Описание")
    url = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Movie(models.Model):
    title = models.CharField(verbose_name="Название фильма", max_length=200)
    tagline = models.CharField(verbose_name="Слоган", max_length=200, default='')
    description = models.TextField(verbose_name="Описание")
    poster = models.ImageField(verbose_name="Постер", upload_to='movie/')
    year = models.SmallIntegerField(verbose_name="Год съёмки")
    country = models.CharField(verbose_name="Страна", max_length=100)
    director = models.ManyToManyField('Actor', verbose_name="Режиссёры", related_name='movie_director')
    actors = models.ManyToManyField('Actor', verbose_name="Актёры", related_name='movie_actors')
    genre = models.ManyToManyField('Genre', verbose_name="Жанр")
    world_premiere = models.DateField(verbose_name="Премьера в мире")
    budget = models.PositiveIntegerField(verbose_name="Бюджет", default=0, help_text="В доллорах США")
    fees_in_usa = models.PositiveIntegerField(verbose_name="Сборы в США", default=0, help_text="В долларах США")
    fees_in_world = models.PositiveIntegerField(verbose_name="Сборы в мире", default=0, help_text="В долларах США")
    category = models.ForeignKey('Category', verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=150, unique=True)
    draft = models.BooleanField(verbose_name="Черновик", default=False)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.review_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class Actor(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    age = models.PositiveSmallIntegerField(verbose_name="Возраст", default=0)
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(verbose_name='Изображение', upload_to='actors/')

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse("director", kwargs={"slug": self.name})

    class Meta:
        verbose_name = 'Актёры и режисёры'
        verbose_name_plural = 'Актёры и режисёры'


class Genre(models.Model):
    name = models.CharField(verbose_name='Название жанра', max_length=150)
    description = models.TextField(verbose_name='Описание')
    url = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Review(models.Model):
    email = models.EmailField(verbose_name="Электронная почта")
    name = models.CharField(verbose_name="Имя", max_length=150)
    text = models.TextField(verbose_name="Отзыв", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey('Movie', verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"отзыв {self.name} к фильму {self.movie}"

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Rating(models.Model):
    ip = models.CharField(verbose_name="IP адрес", max_length=15)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE, verbose_name="Звезда")
    star = models.ForeignKey('RatingStar', on_delete=models.CASCADE, verbose_name="Фильм")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class RatingStar(models.Model):
    value = models.SmallIntegerField(verbose_name="Звезды рейтинга", default=0)

    def __str__(self):
        return f"{self.value}"

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["value"]


class MovieShots(models.Model):
    title = models.CharField(verbose_name="Название", max_length=150)
    description = models.TextField(verbose_name="Описание", default='')
    image = models.ImageField(verbose_name="Фото", upload_to="movie_shots/")
    id_movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"

movies/forms.py
from django import forms

from .models import Review, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""

    class Meta:
        model = Review
        fields = ("name", "email", "text")


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(queryset=RatingStar.objects.all(),
                                  widget=forms.RadioSelect(),
                                  empty_label=None)

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, View
from .models import Movie, Category, Actor, Genre, Rating
from .forms import ReviewForm, RatingForm


class GenreYear:
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class HomePageView(ListView, GenreYear):
    """Список фильмов"""

    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = "movies/movies.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context


class MovieDetailView(DetailView, GenreYear):
    """Подробности о фильме"""

    model = Movie
    slug_field = "url"
    template_name = "movies/movie_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context


class DirectorDetailView(DetailView, GenreYear):
    """Подробности о фильме"""

    model = Actor
    slug_field = "name"
    template_name = "movies/actors_and_directors_detail.html"


class AddReviewView(View):
    """Отзывы"""

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(pk=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent", None))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class FilterMoviesView(GenreYear, ListView):
    template_name = 'movies/movies.html'

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(genre__in=self.request.GET.getlist("genre")) |
            Q(year__in=self.request.GET.getlist("year"))
        ).distinct()
        return queryset


class AddStarRating(View):
    """Добавление рейтинга к фильму"""

    def get_client_ip(self, request):
        x_forwarder_for = request.META.get('HTTP_X_FORWARDER_FOR')
        if x_forwarder_for:
            ip = x_forwarder_for.split(',')[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

templates/movies/actors_and_directors_detail.html
{% extends "movies/base.html" %}
{% load static %}
{% block title %}
    {{ actor.title }}
{% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ actor.name }}
                </h3>
                <ul>
                    <li style="list-style: none">
                                    <span>
                                        <b>Имя:</b>
                                        {{ actor.name }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Возраст:</b>
                                        {{ actor.age }}
                                    </span>
                    </li>
                    {% if actor.movie_director.all %}
                        <li style="list-style: none">
                                    <span>
                                        <b>Режессировала фильмы:</b>
                                        {% for movie in actor.movie_director.all %}
                                            {{ movie.title }};
                                        {% endfor %}
                                    </span>
                        </li>
                    {% endif %}
                    {% if actor.movie_actors.all %}
                        <li style="list-style: none">
                                    <span>
                                        <b>Роли в фильмах:</b>
                                        {% for actor in actor.movie_actors.all %}
                                            {{ actor.title }};
                                        {% endfor %}
                                    </span>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О режиссере {{ actor.name }}</h3>
            <p>
                {% for img in movie.movieshots_set.all %}
                    <img src="{{ img.image.url }}" class="img-movie-shots" alt="{{ img.description }}">
                {% endfor %}
            </p>
            <p class="editContent">{{ actor.description|safe }}</p>
        </div>
    </div>
    </div>
{% endblock %}

templates/movies/base.html
{% extends 'base.html' %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-4">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/_left_sidebar_base.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/directors.html
{% extends "movies/base.html" %}
{% load static %}
{% block title %}
    {{ actor.title }}
{% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ actor.name }}
                </h3>
                <ul>
                    <li style="list-style: none">
                                    <span>
                                        <b>Имя:</b>
                                        {{ actor.name }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Возраст:</b>
                                        {{ actor.age }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Фильмы:</b>
                                        {% for movie in actor.movie_director.all %}
                                            {{ movie.title }};
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Роли:</b>
                                        {% for actor in actor.movie_actors.all %}
                                            {{ actor.title }};
                                        {% endfor %}
                                    </span>
                    </li>

                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О режиссере {{ actor.name }}</h3>
            <p>
                {% for img in movie.movieshots_set.all %}
                    <img src="{{ img.image.url }}" class="img-movie-shots" alt="{{ img.description }}">
                {% endfor %}
            </p>
            <p class="editContent">{{ actor.description|safe }}</p>
        </div>
    </div>
    </div>
{% endblock %}

templates/movies/movie_detail.html
{% extends "movies/base.html" %}
{% load static %}
{% block title %}
    {{ movie.title }}
{% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}
                </h3>
                <ul>
                    <li style="list-style: none">
                                    <span>
                                        <b>Год:</b>
                                        {{ movie.year }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Страна:</b>
                                        {{ movie.country }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Слоган:</b>
                                        {{ movie.tagline }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Режиссеры:</b>
                                        {% for director in movie.director.all %}
                                            <a href="{{ director.get_absolute_url }}">
                                            {{ director.name }}
                                        </a>
                                            ;
                                        {% endfor %}

                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Актеры:</b>
                                        {% for actor in movie.actors.all %}
                                            <a href="{{ actor.get_absolute_url }}">
                                            {{ actor }}
                                            </a>
                                            ;
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Жанр:</b>
                                        {% for genre in movie.genre.all %}
                                            {{ genre }};
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Премьера в мире:</b>
                                        {{ movie.world_primer }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Бюджет:</b>
                                        {{ movie.budget }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Сборы в США:</b>
                                        {{ movie.fees_in_usa }}
                                    </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                                        <b>Сборы в мире:</b>
                                        {{ movie.fees_in_world }}
                                    </span>
                    </li>
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent"></span>
                        </form>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме {{ movie.title }}</h3>
            <p>
                {% for img in movie.movieshots_set.all %}
                    <img src="{{ img.image.url }}" class="img-movie-shots" alt="{{ img.description }}">
                {% endfor %}
            </p>
            <p class="editContent">{{ movie.description|safe }}</p>
            {#            <p class="mt-3 italic-blue editContent"#}
            {#               style="outline: none; cursor: inherit;">#}
            {#                <iframe width="560" height="315"#}
            {#                        src="#"#}
            {#                        frameborder="0" allow="accelerometer; autoplay;#}
            {#                                    encrypted-media; gyroscope; picture-in-picture"#}
            {#                        allowfullscreen>#}
            {#                </iframe>#}
            {#            </p>#}
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">
                                        {{ movie.review_set.count }}
                                    </span>
                        Оставить отзыв
                    </h3>
                    <form action="{% url 'add_view' movie.id %}" method="post" class="mt-4" id="formReview">
                        <div class="form-group editContent">
                            {% csrf_token %}
                            <input type="hidden" name="parent" id="contactparent" value=""></div>
                        <label for="contactcomment" class="editContent">
                            Ваш комментарий *
                        </label>
                        <textarea class="form-control border" name="text"
                                  id="contactcomment" required=""></textarea>
                </div>
                <div class="d-sm-flex">
                    <div class="col-sm-6 form-group p-0 editContent">
                        <label for="contactusername" class="editContent">
                            Имя *
                        </label>
                        <input type="text" class="form-control border" name="name"
                               id="contactusername" required="">
                    </div>
                    <div class="col-sm-6 form-group ml-sm-3 editContent">
                        <label for="contactemail" class="editContent">
                            Email *
                        </label>
                        <input type="email" class="form-control border" name="email"
                               id="contactemail" required="">
                    </div>
                </div>
                <button type="submit"
                        class="mt-3 btn btn-success btn-block py-3">
                    Отправить
                </button>
                </form>
            </div>
            <!--  //contact form grid ends here -->
        </div>
        {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}',
                            '{{ review.id }}')">
                        Ответить
                    </a>
                    {% for rev in review.review_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te2.jpg' %}" class="img-fluid" alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rev.name }}</h5>
                                <p class="mt-2 editContent">{{ rev.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

templates/movies/movies.html
{% extends 'movies/base.html' %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for  movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">{{ movie.title }}</a>
                            </h4>
                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a></li>
                                <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock movie %}